version: '3'
services:
    parity:
        image: parity/parity:nightly
        volumes:
            - ./io.parity.ethereum:/mnt
        ports:
            - "127.0.0.1:8080:8080"
            - "127.0.0.1:8180:8180"
            - "127.0.0.1:8545:8545"
            - "127.0.0.1:8546:8546"
        logging:
            options:
                max-file: "1"
                max-size: "1g"
        command: --base-path /mnt --unsafe-expose --chain ropsten --bootnodes "enode://20c9ad97c081d63397d7b685a412227a40e23c8bdc6688c6f37e97cfbc22d2b4d1db1510d8f61e6a8866ad7f0e17c02b14182d37ea7c3c8b9c2683aeb6b733a1@52.169.14.227:30303,enode://6ce05930c72abc632c58e2e4324f7c7ea478cec0ed4fa2528982cf34483094e9cbc9216e7aa349691242576d552a2a56aaeae426c5303ded677ce455ba1acd9d@13.84.180.240:30303"

    raiden:
        build: ./raiden
        volumes:
            - ./raiden/repo:/apps/raiden
            - ./io.parity.ethereum/keys/test:/opt/keys
            - ./key.txt:/key.txt:ro
        logging:
            options:
                max-file: "1"
                max-size: "1g"
        links:
            - parity
        ports:
            - "127.0.0.1:5001:5001"
            - "127.0.0.1:40001:40001/udp"
        environment:
            - RAIDEN_ADDRESS=0xb0d5eeaeb7b084a2ba92c24b79f4f2d079a3062b
        entrypoint:
            - /bin/sh
            - -c
        command:
            - python2 setup.py develop && exec raiden --keystore-path /opt/keys --eth-rpc-endpoint parity:8545 --rpc --api-address 0.0.0.0:5001 --password-file /key.txt

    webui:
        image: node:alpine
        volumes:
            - ./raiden/repo/raiden/raidenwebui:/app
            - ./proxy.config.json:/usr/src/app/proxy.config.json:ro
        working_dir: /app
        user: 1000:1000
        links:
            - raiden
            - parity
        expose:
            - "4200"
        ports:
            - "127.0.0.1:4200:4200"
        entrypoint:
            - /bin/sh
            - -c
        command:
            - npm i && exec ./node_modules/.bin/ng serve --host=0.0.0.0

